version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-hub:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  maven-tests:
    image: maven:3.8.1-jdk-11
    container_name: maven-tests
    depends_on:
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/sh -c "
      while ! curl -sS selenium-hub:4444/wd/hub/status | grep -q 'ready'; do
        echo 'Waiting for selenium-hub...';
        sleep 2;
      done;
      mkdir -p target/allure-results;
      mvn clean test -DproductName=${PRODUCT_NAME} -DbrowserEnv="remote" || true;
      mvn allure:report;
      mvn allure:serve -Dallure.serve.port=4040"
    ports:
      - "4040:4040"
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
